# Generated by Django 4.1.3 on 2022-11-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imovel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hospedes", models.IntegerField()),
                ("banheiros", models.IntegerField()),
                ("pet", models.BooleanField(default=False)),
                ("valor_limpeza", models.DecimalField(decimal_places=2, max_digits=8)),
                ("data_ativacao", models.DateField()),
                ("criacao", models.DateTimeField(auto_now_add=True)),
                ("atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
