# Generated by Django 4.1.3 on 2022-11-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='comentario',
            field=models.TextField(max_length=255),
        ),
    ]
