# Generated by Django 4.1.3 on 2022-11-15 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imoveis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("plataforma", models.CharField(max_length=255)),
                ("taxa", models.DecimalField(decimal_places=2, max_digits=8)),
                ("criacao", models.DateTimeField(auto_now_add=True)),
                ("atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "imovel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="imoveis.imovel"
                    ),
                ),
            ],
        ),
    ]
